cypress-master/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  root to: 'home#index'

  get '404', to: 'application#page_not_found'
  get '500', to: 'application#server_error'

  resources :vendors do
    post :favorite
    resources :products, only: %i[show index new create edit update destroy favorite] do
      post :favorite
      member do
        get :patients
        get :report
        get :supplemental_test_artifact
      end
    end
  end

  resources :products, only: %i[show edit update destroy favorite] do
    post :favorite
    resources :product_tests, only: %i[index show]
    resources :checklist_tests, only: %i[create show update destroy] do
      member do
        get :print_criteria
      end
    end
    member do
      get :download_full_test_deck
    end
  end

  resources :checklist_tests, only: %i[create show update destroy] do
    member do
      get 'measure/:measure_id', action: 'measure', as: 'measure'
    end
  end

  resources :product_tests, only: [:show] do
    member do
      get :patients
      get :html_patients
    end
    resources :tasks, only: %i[index show]
    resources :records, only: %i[index show] do
      collection do
        resources :tasks, :controller => :records, :only => [:by_filter_task] do
          get :by_filter_task
        end
      end
    end
  end

  resources :tasks, :only => [:show] do
    member do
      get :good_results
    end
    resources :test_executions, :only => %i[index show new create destroy]
  end

  resources :test_executions, :only => %i[show destroy] do
    member do
      get 'file_result/:file_name', :action => 'file_result', :as => 'file_result'
    end
  end

  resources :bundles, :only => %i[index show] do
    resources :records, :only => %i[index show] do
      collection do
        get :by_measure
      end
    end
    resources :measures, :only => [:index] do
      collection do
        get :grouped
        get 'filtered(/:filter)', :to => 'measures#filtered'
      end
    end
  end

  resources :records, :only => %i[index show] do
    collection do
      get :download_mpl
    end
  end

  resource :admin, :only => [:show], :controller => 'admin'

  namespace 'admin' do
    resource :settings, :only => %i[show edit update]
    get 'users/send_invitation'
    get :download_logs
    resources :users, :except => %i[new create] do
      member do
        get :unlock
        get :toggle_approved
      end
    end
    resources :bundles, :except => %i[show edit update] do
      member do
        post :set_default
        post :deprecate
      end
    end
    resources :trackers, :only => [:destroy]
  end

  get 'terms_and_conditions' => 'static_pages#terms_and_conditions'
end

cypress-master/app/models/test_execution.rb
class TestExecution
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Attributes::Dynamic
  include GlobalID::Identification
  # include Cypress::ErrorCollector

  field :state, :type => Symbol, :default => :pending
  field :expected_results, :type => Hash
  field :reported_results, :type => Hash
  field :qrda_type, :type => String
  field :backtrace, :type => String
  # a sibling test execution is a c3 test execution if the current execution is a c1 or c2 execution. vice versa
  #   and nil if c3 execution does not exist
  field :sibling_execution_id, :type => String

  embeds_many :execution_errors
  has_one :artifact, :autosave => true, :dependent => :destroy
  belongs_to :user
  belongs_to :task, :touch => true

  def build_document(file)
    doc = Nokogiri::XML(file)
    doc.root.add_namespace_definition('cda', 'urn:hl7-org:v3')
    doc.root.add_namespace_definition('sdtc', 'urn:hl7-org:sdtc')
    doc
  end

  # I dont think this belongs here and it will need to eventually be moved to a
  # more approperiate location
  def validate_artifact(validators, artifact, options = {})
    file_count = 0

    # TODO: R2P: change R/P model through all validators
    artifact.each_file do |name, file|
      doc = build_document(file)
      merged_options = options.merge(:file_name => name)
      validators.each do |validator|
        validator.validate(doc, merged_options)
        break unless validator.can_continue
      end
      file_count += 1
    end
    validators.each do |validator|
      execution_errors.concat validator.errors
    end
    conditionally_add_task_specific_errors(file_count)
    execution_errors.only_errors.count.positive? ? fail : pass
  rescue => e
    errored(e)
    logger.error("Encountered an exception in Test Execution #{id}: #{e.message}, backgrace:\n#{e.backtrace}")
  end

  def conditionally_add_task_specific_errors(file_count)
    if (task.is_a?(C1Task) && task.product_test.product.c1_test) && file_count != task.patients.count
      execution_errors.build(:message => "#{task.patients.count} files expected but was #{file_count}",
                             :msg_type => :error, :validator_type => :result_validation, :validator => :smoking_gun)
    end
    task.product_test.build_execution_errors_for_incomplete_checked_criteria(self) if task.is_a?(C1ChecklistTask)
  end

  # Get the expected result for a particular measure
  def expected_result(measure)
    (expected_results || product_test.expected_results || {})[measure.key] || {}
  end

  # Get the expected result for a particular measure
  def reported_result(measure)
    (reported_results || {})[measure.key] || {}
  end

  def passing?
    state == :passed
  end

  def failing?
    state == :failed
  end

  def errored?
    state == :errored
  end

  def incomplete?
    (!passing? && !failing? && !errored?)
  end

  def pass
    self.state = :passed
    save
  end

  def fail
    self.state = :failed
    save
  end

  def errored(e = nil)
    self.state = :errored
    self.backtrace = e.message + "\n" + e.backtrace.join("\n")
    save
  end

  def sibling_execution
    TestExecution.find(sibling_execution_id)
  rescue
    nil
  end

  def status
    return 'passing' if passing?
    return 'failing' if failing?
    return 'errored' if errored?
    'incomplete'
  end

  # returns combined status including c3 test execution
  # returns passing if both passing, incomplete if either incomplete, failing if both complete and at least one failing
  def status_with_sibling
    sibling = sibling_execution
    return status unless sibling
    return status if status == sibling.status
    return 'incomplete' if incomplete? || sibling.incomplete?
    return 'failing' if failing? || sibling.failing?
    return 'errored' if errored? || sibling.errored?
    'failing' # failing if status's do not match
  end

  def last_updated_with_sibling
    sibling = sibling_execution
    return updated_at unless sibling
    [updated_at, sibling.updated_at].max
  end

  # checks
  def executions_pending?
    c3_execution = sibling_execution
    return state == :pending unless c3_execution
    state == :pending || c3_execution.state == :pending
  end

  def errored_or_sibling_errored?
    errored? || (sibling_execution&.errored?)
  end

  def incomplete_or_sibling_incomplete?
    incomplete? || (sibling_execution&.incomplete?)
  end
end

cypress-master/app/controllers/test_executions_controller.rb
class TestExecutionsController < ApplicationController
  include API::Controller
  include TestExecutionsHelper
  include Cypress::ErrorCollector

  before_action :set_test_execution, only: %i[show destroy file_result]
  before_action :set_task, only: %i[index new create]
  before_action :set_task_from_test_execution, only: %i[show file_result]
  before_action :set_product_test_from_task, only: %i[show new file_result]
  before_action :add_breadcrumbs, only: %i[show new]
  before_action :check_bundle_deprecated, only: %i[show index new]

  respond_to :js, only: %i[show create]

  def index
    @test_executions = @task.test_executions
    respond_with(@test_executions.to_a)
  end

  def create
    authorize! :execute_task, @task.product_test.product.vendor
    @test_execution = @task.execute(results_params, current_user)
    @curr_task = Task.find(params[:task_id])
    respond_with(@test_execution) do |f|
      if @task.is_a? C1ChecklistTask
        f.html { redirect_to product_checklist_test_path(@task.product_test.product, @task.product_test) }
      else
        f.html { redirect_to task_test_execution_path(task_id: @task.id, id: @test_execution.id) }
      end
    end
  rescue Mongoid::Errors::Validations
    rescue_create
  end

  def new
    authorize! :execute_task, @product_test.product.vendor
    if @task.most_recent_execution
      redirect_to task_test_execution_path(task_id: @task.id, id: @task.most_recent_execution.id)
      return
    end
    render :show
  end

  def show
    authorize! :read, @task.product_test.product.vendor
    respond_with(@test_execution)
  end

  def destroy
    authorize! :delete, @test_execution.task.product_test.product.vendor
    @test_execution.destroy!
    render :nothing => true, :status => :no_content
  end

  def file_result
    authorize! :execute_task, @product_test.product.vendor
    add_breadcrumbs
    add_breadcrumb "File Results: #{route_file_name(params[:file_name])}"
    @file_name, @error_result = file_name_and_error_result_from_execution(@test_execution)
  end

  private

  def rescue_create
    alert = 'Invalid file upload. Please make sure you upload an XML or zip file.'
    error_response = { :errors => [{ :field => 'results',
                                     :messages => ['invalid file upload. upload a zip for QRDA Category I or XML for QRDA Category III'] }] }
    respond_with(@test_execution) do |f|
      f.html { redirect_to new_task_test_execution_path(:task_id => @task.id), :flash => { :alert => alert.html_safe } }
      f.json { render :json => error_response, :status => :unprocessable_entity }
      f.xml  { render :xml => error_response[:errors].to_xml(:root => :errors, :skip_types => true), :status => :unprocessable_entity }
    end
  end

  def set_task_from_test_execution
    @task = @test_execution.task
  end

  def set_product_test_from_task
    @product_test = @task.product_test
  end

  def add_breadcrumbs
    product = @product_test.product
    add_breadcrumb 'Dashboard', :vendors_path
    add_breadcrumb 'Vendor: ' + product.vendor_name, vendor_path(product.vendor)
    add_breadcrumb 'Product: ' + product.name, vendor_product_path(product.vendor, product)
    add_breadcrumb 'Record Sample Test', product_checklist_test_path(product, @product_test) if @product_test.is_a? ChecklistTest
    add_test_execution_breadcrumb
  end

  def add_test_execution_breadcrumb
    if @task.most_recent_execution
      add_breadcrumb 'Test: ' + @product_test.name, task_test_execution_path(:task_id => @task.id, :id => @task.most_recent_execution.id)
    else
      add_breadcrumb 'Test: ' + @product_test.name, ''
    end
  end

  def results_params
    # reqests from outside test execution page will have :results inside :test_execution in params
    if params[:results]
      params[:results]
    elsif params[:test_execution]
      params[:test_execution][:results]
    end
  end
end

cypress-master/app/helpers/test_executions_helper.rb
module TestExecutionsHelper
  include TestExecutionsResultsHelper
  include Cypress::ErrorCollector

  def displaying_cat1?(task)
    task.is_a?(C1Task) || task.is_a?(Cat1FilterTask) || task.is_a?(C1ChecklistTask)
  end

  def task_type_to_title(task_type, c3)
    case task_type
    when 'C1Task'
      if @product_test.c1_test
        c3 ? 'C1 and C3' : 'C1'
      else
        'C3 (QRDA-I)'
      end
    when 'C2Task'
      if @product_test.c2_test
        c3 ? 'C2 and C3' : 'C2'
      else
        'C3 (QRDA-III)'
      end
    when 'Cat1FilterTask' then 'QRDA Category I'
    when 'Cat3FilterTask' then 'QRDA Category III'
    end
  end

  # task_type is String and c3_task is boolean
  # returns an array of booleans [c1, c2, c3, c4]. true if page is testing these certification types
  def current_certifications(task_type, c3_task)
    return [false, false, false, true] if %w[Cat1FilterTask Cat3FilterTask].include?(task_type)
    [task_type == 'C1Task' || task_type == 'C1ChecklistTask', task_type == 'C2Task', c3_task, false]
  end

  # returns the number of each type of error
  def get_error_counts(execution, task)
    h = Hash[['QRDA Errors', 'Reporting Errors', 'Submission Errors', 'Warnings'].zip(get_error_counts_helper(execution))]
    h.except!('Submission Errors', 'Warnings') unless task.product_test.product.c3_test
    h
  end

  def get_error_counts_helper(execution)
    return ['--', '--', '--'] unless execution&.failing?
    qrda = execution.execution_errors.qrda_errors.count
    reporting = execution.execution_errors.reporting_errors.count
    submit_errors = submit_warnings = 0
    if execution.sibling_execution
      submit_errors = execution.sibling_execution.execution_errors.only_errors.count
      submit_warnings = execution.sibling_execution.execution_errors.only_warnings.count
    end
    [qrda, reporting, submit_errors, submit_warnings]
  end

  def date_of_execution(execution)
    display_time_to_minutes(execution.created_at)
  end

  def get_title_message(test, task)
    msg = ''
    if test.is_a? MeasureTest
      msg << task_type_to_title(task._type, task.product_test.product.c3_test)
      msg << ' certification'
      msg << 's' if test.product.c3_test
    else
      msg << 'CQM Filter'
      filters = test.options.filters.keys
      msg << 's' if filters.count > 1
      msg << " #{filters.join('/').titleize}"
    end
    msg << " for #{test.cms_id} #{test.name}"
  end

  def get_upload_type(is_displaying_cat1)
    is_displaying_cat1 ? 'zip file of QRDA Category I documents' : 'QRDA Category III XML document'
  end

  def execution_failure_message(execution)
    should_display_c3 = execution.sibling_execution ? true : false
    combined_errors = should_display_c3 ? execution.execution_errors + execution.sibling_execution.execution_errors : execution.execution_errors

    all_warnings, all_errors = combined_errors.partition { |e| e.msg_type == :warning }

    failure_message = "Failed with #{pluralize(all_errors.count, 'error')}"
    failure_message += " and #{pluralize(all_warnings.uniq { |e| [e.message, e.location, e.file_name] }.count, 'warning')}" if all_warnings.any?

    failure_message
  end

  def execution_status_class(execution)
    case execution.status_with_sibling
    when 'incomplete' then 'info'
    when 'passing' then 'success'
    when 'errored' then 'warning'
    else 'danger'
    end
  end

  def info_title_for_product_test(product_test)
    case product_test
    when MeasureTest then 'Measure Test Information'
    when FilteringTest then 'Filtering Test Information'
    when ChecklistTest then 'Record Sample Test Information'
    else 'Test Information'
    end
  end

  def route_file_name(file_name)
    file_name.dup.tr('.', '_').force_encoding('UTF-8')
  end

  def iterate_task(task, direction)
    tests = task.product_test.product.product_tests
    tests = if task.is_a?(Cat1FilterTask) || task.is_a?(Cat3FilterTask)
              tests.filtering_tests.sort_by { |t| cms_int(t.cms_id) }
            else
              tests.measure_tests.sort_by { |t| cms_int(t.cms_id) }
            end
    index = tests.index(task.product_test)
    next_test = if direction == 'next'
                  tests[(index + 1) % tests.count]
                else
                  tests[(index - 1 + tests.count) % tests.count]
                end
    next_test.tasks.find_by(_type: task._type)
  end

  def should_display_expected_results(task)
    !hide_patient_calculation? && (task.is_a?(C2Task) || task.product_test.is_a?(FilteringTest))
  end
end

cypress-master/app/views/test_executions/_execution_download.html.erb
<%
#
# renders the download test deck button if product_test is ready
#
# must specify local variable "product_test"
#
%>

<div id = 'display_execution_download'>
  <% if product_test.state == :ready %>
    <p>Download and import this data into your EHR clinical quality measure calculator.</p>
    <%= form_tag(patients_product_test_path(product_test), method: 'get') do |f| %>
      <%= hidden_field_tag :id, :value => product_test.id %>
      <%= button_tag(type: 'submit', class: 'btn btn-info') do %>
        <%= icon('fas fa-fw', 'download', :"aria-hidden" => true) %> Download QRDA Category I (.zip)
      <% end %>
    <% end %>
  <% elsif product_test.state == :errored %>
    <p><%= icon('fas', 'exlamation-triangle', :"aria-hidden" => true) %>Cypress encountered an internal error while building this measure. Please contact the Cypress team at https://github.com/projectcypress/cypress/issues, and include the text below:</p>
    <code>
      <%= product_test.status_message %>
    </code>
  <% else %>
    <p><%= icon('fas fa-fw fa-spin', 'sync-alt', :"aria-hidden" => true) %> Cypress is building test patients for this measure. You will be able to download a zip file of QRDA Category I documents. </p>
    <script>
      $.ajax({url: "<%= request.env['PATH_INFO'] %>", type: "GET", dataType: 'script', data: { partial: 'execution_download' }});
    </script>
  <% end %>
</div>

cypress-master/app/views/test_executions/_execution_results.html.erb
<%
#
# renders the errors for the most recent test execution for the given task.
#
# must specify local variable "execution"
#
%>

<% if execution.status_with_sibling == 'incomplete' %>
  <p class="lead row bg-info execution-status"><%= icon('fas fa-fw fa-spin text-info', 'sync-alt', :"aria-hidden" => true) %> In Progress</p>
  <p>You do not need to reload your browser. Results will automatically display when the tests are done running.</p>
  <% # ajax contacts test_execution's show controller action with format: 'js'. controller then directs to show.js.erb which will wait, then re-render %>
  <script>
    $.ajax({url: "<%= request.env['PATH_INFO'] %>", type: "GET", dataType: 'script', data: { partial: 'execution_results' }});
  </script>

<% else %>
  <% if passing = execution.status_with_sibling == 'passing'%>
    <%= render partial: 'test_executions/results/passing_result', locals: { execution: execution, execution_type: nil } %>
  <% elsif execution.errored_or_sibling_errored? %>
    <% [execution, execution.sibling_execution].compact.each do |ex| %>
      <% ex_type = ex.task._type[0, 2] # get first two letters e.g. C1 or C3 %>
      <% if ex.errored? %>
        <p class="lead row bg-warning execution-status"><%= icon('fas fa-fw text-warning', 'exclamation-circle', :"aria-hidden" => true) %> <%= ex_type %> Execution: An internal error occurred</p>
      <% elsif ex.passing? %>
        <%= render partial: 'test_executions/results/passing_result', locals: { execution: ex, execution_type: ex_type } %>
      <% elsif ex.failing? %>
        <p class="lead row bg-danger execution-status">
          <%= icon('fas fa-fw text-danger', 'times-circle', :"aria-hidden" => true) %> <%= ex_type %> Execution:
          <%= execution_failure_message(ex) %>
        </p>
      <% end %>
    <% end %>
  <% else %>
    <p class="lead row bg-danger execution-status">
      <%= icon('fas fa-fw text-danger', 'times-circle', :"aria-hidden" => true) %>
      <%= execution_failure_message(execution) %>
    </p>
  <% end %>

  <% collected_errors = collected_errors(execution) %>

  <% if collected_errors[:exception] %>
    <h2>An internal error occurred when loading this page</h2>
    <p><%= collected_errors[:exception] %></p>
    <span class="help-block">Please report this issue to the Cypress team at <a href="https://github.com/projectcypress/cypress/issues" target="_blank">https://github.com/projectcypress/cypress/issues</a> and include: the uploaded file, the measure being tested, and the error message received.</span>
  <% end %>

  <% if collected_errors.nonfile.count.positive? %>
    <h2>Missing or Duplicate Files</h2>
    <ul class="fa-ul">
      <% collected_errors.nonfile.each do |error_message| %>
        <li><%= icon('fas fa-li', 'times', :"aria-hidden" => true) %> <%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

  <% if collected_errors.files.values.any? { |err| err.count.positive? } %>
    <h2><%= "Errors and " unless passing %>Warnings</h2>
    <div id="xml-tabs" class="hidden file-error-tabs short-tabs">
      <ul>
        <% collected_errors.files.each do |file_name, error_result| %>
          <li>
            <a href=<%= "##{execution.id}_#{file_name.gsub(/[\W]/,'_')}" %>>
              <% total_errors = error_result.keys.map{ |s| error_result[s].execution_errors.count }.reduce(&:+) %>
              <% if total_errors.positive? %>
                <div class="file-name">
                  <% if error_result.keys.any? { |s| s != 'Other Warnings' && s != 'CMS Warnings' && error_result[s].execution_errors.count.positive?} %>
                    <%= icon('fas fa-fw text-danger', 'times', :"aria-hidden" => true) %>
                  <% else %>
                    <%= icon('fas fa-fw text-warning', 'exclamation-triangle', :"aria-hidden" => true) %>
                  <% end %>
                  <%= file_name %>
                </div>
                <div class="file-badge">
                  <span class="badge pull-right">
                    <%= total_errors %>
                    <span class="sr-only">errors</span>
                  </span>
                </div>
              <% else %>
                <div class="file-name">
                  <%= icon('fas fa-fw text-success', 'check', :"aria-hidden" => true) %>
                  <%= file_name %>
                  <span class="sr-only">no errors</span>
                </div>
              <% end %>
            </a>
          </li>
        <% end %>
      </ul>

      <% collected_errors.files.each do |file_name, error_result| %>
        <div id=<%= "#{execution.id}_#{file_name.gsub(/[\W]/,'_')}" %>>
          <%= render partial: 'test_executions/results/execution_results_for_file', locals: { execution: execution, file_name: file_name, error_result: error_result, is_passing: passing, on_execution_show_page: true } %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

cypress-master/app/views/test_executions/_execution_upload.html.erb
<%

# inputs:
#
#   task (c1task or c2task)
#   disable

%>

<% if disable %>
  <% disable_msg ||= 'Fill in the Data Criteria fields before you upload results from your EHR system.' %>
  <p>
    <span class = 'text-danger'>
      <%= disable_msg %>
    </span>
  </p>
<% else %>
  <p class = 'description' id='execution_upload_label'>
    <%= "Upload results from the EHR system in the form of a #{get_upload_type(displaying_cat1?(task))} to get test results. This will automatically run a test execution." %>
  </p>
<% end %>

<% if displaying_cat1?(task) %>
  <% accept_type = 'application/zip' %>
<% else %>
  <% accept_type = 'text/xml' %>
<% end %>
<%= form_for(TestExecution.new, :html => { method: :post, :multipart => true }, url: task_test_executions_path(task)) do |f| %>
  <div class="fileinput fileinput-new input-group" data-provides="fileinput">
    <div class="form-control" data-trigger="fileinput">
      <%= icon('fas fa-fw fileinput-exists', 'file', :"aria-hidden" => true) %>
      <span class="fileinput-filename"></span>
    </div>
    <% if disable %>
      <span class="input-group-addon btn btn-info btn-file disabled">
    <% else %>
      <span class="input-group-addon btn btn-info btn-file active">
    <% end %>
      <span class="fileinput-new" data-trigger="fileinput"><%= icon('fas', 'mouse-pointer', :"aria-hidden" => true) %> Select file</span>
      <span class="fileinput-exists" data-trigger="fileinput"><%= icon('fas', 'sync-alt', :"aria-hidden" => true) %> Change</span>
      <%= file_field_tag :results, class: 'upload-results hidden', :disabled => disable, accept: accept_type, :aria => { label: 'execution_upload_label', hidden: true } %>
    </span>
    <a id = 'submit-upload' class="input-group-addon fileinput-exists btn btn-success"><%= icon('fas', 'upload', :"aria-hidden" => true) %> Upload</a>
  </div>
<% end %>

cypress-master/app/views/test_executions/_expected_result_icon.html.erb
<% if result && result.positive? %>
  <span class="sr-only">Pass</span>
  <span class="result-marker">
    <strong class="result-text"><span class="sr-only">value of </span><%= result %></strong>
  </span>
<% else %>
  <span class="sr-only">Fail</span>
  <%= icon('far fa-2x empty-marker', 'circle', :"aria-hidden" => true) %>
<% end %>

cypress-master/app/views/test_executions/_expected_results.html.erb
<% if task.product_test_expected_results %>
<h1>Expected Aggregate Results</h1>
<table class="table table-condensed table-hover">
  <thead>
    <tr>
      <th scope="col">Measure Name</th>
      <% population_keys = task.product_test_expected_results.first[1].population_ids.keys %>
      <% population_keys.each do |population| %>
        <th scope="col" class="text-center"><%= population_label(task.bundle, population) %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <!-- Only show records that are part of the measures IPP-->
    <% task.product_test_expected_results.each do |expected_result| %>
      <tr>
        <% mes = if task.product_test_expected_results.size > 1
                    HealthDataStandards::CQM::Measure.where(hqmf_id: expected_result[1]['measure_id'], sub_id: expected_result[0][-1,1]).first
                 else
                    HealthDataStandards::CQM::Measure.where(hqmf_id: expected_result[1]['measure_id']).first
                 end %>
        <td><%= mes.subtitle.nil? ? "#{mes.name}" : "#{mes.name} - #{mes.subtitle}" %></td>
        <% expected_result[1].population_ids.keys().each do |population| %>
          <% if population_keys.include? population %>
            <td class="text-center">
              <%= render 'expected_result_icon', :result => expected_result[1][population] %>
            </td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

cypress-master/app/views/test_executions/_filter_instructions.html.erb
<%

# local variable 'task'. must be a FilteringTest

%>

<p class="description">Remove any patients not meeting the following criteria.</p>
<% task.product_test.options.filters.map do |filter_name, val| %>
  <dl class="filters-list">
    <dt><%= display_filter_title(filter_name, task) %></dt>
    <dd>
      <% filter_values = display_filter_val(filter_name, val) %>
      <% filter_values.each do |filter_val| %>
        <% if filter_val.is_a?(Hash) %>
          <% filter_val.each_pair do |value_key, value_val| %>
            <p><strong><%= value_key %></strong>
            <%= value_val %></p>
          <% end %>
        <% else %>
          <%= filter_val %>
        <% end %>
      <% end %>

    </dd>
  </dl>
<% end %>

cypress-master/app/views/test_executions/_test_info.html.erb
<%

# local variable 'task'

%>

<div class = 'col-sm-4'>
  <h1><%= info_title_for_product_test(task.product_test) %></h1>
  <% unless task.product_test.is_a? ChecklistTest %>
    <strong>Measure: </strong><span><%= task.product_test_name %></span><br/>
  <% end %>
  <strong>HQMF ID: </strong><span><%= task.measure_ids.join(',') %></span><br/>
  <% unless task.product_test.is_a? ChecklistTest %>
    <strong>CMS ID: </strong><span><%= task.product_test_cms_id%></span><span><%= link_to " (eCQM Specification)", "https://ecqi.healthit.gov/ecqm/measures/#{padded_cms_id(task.product_test_cms_id)}", :target => "_blank", :id => "ecqm-link" %></span><br/>
  <% end %>

  <% # display provider information if the product test is a measure test %>
  <% if task.product_test.is_a? MeasureTest %>
    <% provider = task.product_test.provider %>
    <% unless provider.nil? %>
      <br/>
      <% { 'Name' => "#{provider.family_name}, #{provider.given_name}", 'NPI' => provider.npi, 'TIN' => provider.tin, 'CCN' => provider.ccn }.each do |label, value| %>
        <strong><%= "Provider #{label}: " %></strong><span><%= value %></span><br/>
      <% end %>
    <% end %>
  <% end %>

  <br/>

  <% unless task.is_a? C1ChecklistTask %>
    <%= link_to 'View Patients', { controller: 'records', task_id: task.id}, method: :get %>
    <% if (task.is_a?(Cat1FilterTask) || task.is_a?(Cat3FilterTask)) && should_display_expected_results(task) %>
      <br/>
      <%= link_to 'View Expected Result', product_test_task_by_filter_task_path(task.product_test, task),  method: :get %>
    <% end %>
    <% if Settings.current.enable_debug_features %>
      <br/>
      <%= link_to 'Get Known Good Result', good_results_task_path(task), data: { no_turbolink: true } %>
    <% end %>
  <% end %>
</div>