cypress-master/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  root to: 'home#index'

  get '404', to: 'application#page_not_found'
  get '500', to: 'application#server_error'

  resources :vendors do
    post :favorite
    resources :products, only: %i[show index new create edit update destroy favorite] do
      post :favorite
      member do
        get :patients
        get :report
        get :supplemental_test_artifact
      end
    end
  end

  resources :products, only: %i[show edit update destroy favorite] do
    post :favorite
    resources :product_tests, only: %i[index show]
    resources :checklist_tests, only: %i[create show update destroy] do
      member do
        get :print_criteria
      end
    end
    member do
      get :download_full_test_deck
    end
  end

  resources :checklist_tests, only: %i[create show update destroy] do
    member do
      get 'measure/:measure_id', action: 'measure', as: 'measure'
    end
  end

  resources :product_tests, only: [:show] do
    member do
      get :patients
      get :html_patients
    end
    resources :tasks, only: %i[index show]
    resources :records, only: %i[index show] do
      collection do
        resources :tasks, :controller => :records, :only => [:by_filter_task] do
          get :by_filter_task
        end
      end
    end
  end

  resources :tasks, :only => [:show] do
    member do
      get :good_results
    end
    resources :test_executions, :only => %i[index show new create destroy]
  end

  resources :test_executions, :only => %i[show destroy] do
    member do
      get 'file_result/:file_name', :action => 'file_result', :as => 'file_result'
    end
  end

  resources :bundles, :only => %i[index show] do
    resources :records, :only => %i[index show] do
      collection do
        get :by_measure
      end
    end
    resources :measures, :only => [:index] do
      collection do
        get :grouped
        get 'filtered(/:filter)', :to => 'measures#filtered'
      end
    end
  end

  resources :records, :only => %i[index show] do
    collection do
      get :download_mpl
    end
  end

  resource :admin, :only => [:show], :controller => 'admin'

  namespace 'admin' do
    resource :settings, :only => %i[show edit update]
    get 'users/send_invitation'
    get :download_logs
    resources :users, :except => %i[new create] do
      member do
        get :unlock
        get :toggle_approved
      end
    end
    resources :bundles, :except => %i[show edit update] do
      member do
        post :set_default
        post :deprecate
      end
    end
    resources :trackers, :only => [:destroy]
  end

  get 'terms_and_conditions' => 'static_pages#terms_and_conditions'
end

cypress-master/app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record_source, only: %i[index show by_measure by_filter_task]

  respond_to :js, only: [:index]

  def index
    unless Bundle.default
      @patients = []
      @measures = []
      add_breadcrumb 'Master Patient List', :records

      return
    end

    return redirect_to bundle_records_path(Bundle.default) unless params[:bundle_id] || params[:task_id]
    # TODO: Only show measures where there are patient results. CMS32v4 sub id c and d have no patients, for example.
    @patients = @source.patients.order_by(first: 'asc')
    # create json with the display_name and url for each measure
    @measure_dropdown = Rails.cache.fetch("#{@source.cache_key}/measure_dropdown") do
      @source.measures
             .order_by(cms_int: 1, sub_id: 1)
             .map do |m|
        { label: m.display_name,
          value: by_measure_bundle_records_path(@bundle, measure_id: m.hqmf_id, sub_id: m.sub_id) }
      end.to_json.html_safe
    end
    @mpl_bundle = Bundle.find(params[:mpl_bundle_id]) if params[:mpl_bundle_id]
  end

  def show
    @record = @source.patients.find(params[:id])
    @results = @record.calculation_results
    @measures = @source.measures.where(:_id.in => @results.map(&:measure_id))
    @continuous_measures = @measures.where(continuous_variable: true).sort_by { |m| [m.cms_int, m.sub_id] }
    @non_continuous_measures = @measures.where(continuous_variable: false).sort_by { |m| [m.cms_int, m.sub_id] }
    expires_in 1.week, public: true
    add_breadcrumb 'Patient: ' + @record.first_names + ' ' + @record.familyName, :record_path
  end

  def by_measure
    @patients = @source.patients.includes(:calculation_results)
    if params[:measure_id]
      @measure = @source.measures.find_by(hqmf_id: params[:measure_id], sub_id: params[:sub_id])
      expires_in 1.week, public: true
    end
  end

  def by_filter_task
    @patients = Patient.where(:_id.in => @product_test.filtered_patients.map(&:id))
  end

  def download_mpl
    if BSON::ObjectId.legal?(params[:format])
      bundle = Bundle.find(BSON::ObjectId.from_string(params[:format]))

      if bundle.mpl_status != :ready
        flash[:info] = 'This bundle is currently preparing for download.'
        redirect_to :back
      else
        file = File.new(bundle.mpl_path)
        expires_in 1.month, public: true
        send_data file.read, type: 'application/zip', disposition: 'attachment', filename: "bundle_#{bundle.version}_mpl.zip"
      end
    else
      render :nothing => true, :status => :bad_request
    end
  end

  private

  def set_record_source
    if params[:bundle_id]
      set_record_source_bundle
    elsif params[:task_id]
      set_record_source_product_test
    else
      # TODO: figure out what scenarios lead to this branch and fix them
      @bundle = Bundle.default
      @source = @bundle
      return unless @bundle
      add_breadcrumb 'Master Patient List', bundle_records_path(@bundle)
      @title = 'Master Patient List'
    end
  end

  # sets the record source to bundle for the master patient list
  def set_record_source_bundle
    @source = @bundle = Bundle.available.find(params[:bundle_id])
    add_breadcrumb 'Master Patient List', bundle_records_path(@bundle)
    @title = 'Master Patient List'
  end

  # sets the record source to product_test for the patients for a measure test
  def set_record_source_product_test
    @task = Task.find(params[:task_id])
    @product_test = @task.product_test
    @bundle = @product_test.bundle
    authorize! :read, @product_test.product.vendor
    @measure = @product_test.measures.where(:sub_id => params['sub_id']).first
    @measure ||= @product_test.measures.first
    @source = @product_test
    breadcrumbs_for_test_path
    @title = "#{@task.product_test.product.name} #{@task._type.titleize} #{@task.product_test.measures.first.cms_id} Patients"
  end

  def breadcrumbs_for_test_path
    add_breadcrumb 'Dashboard', :vendors_path
    add_breadcrumb 'Vendor: ' + @product_test.product.vendor.name, vendor_path(@product_test.product.vendor)
    add_breadcrumb 'Product: ' + @product_test.product_name, vendor_product_path(@product_test.product.vendor, @product_test.product)
    add_breadcrumb 'Test: ' + @product_test.name, new_task_test_execution_path(@task.id)
    add_breadcrumb 'Patient List', records_path(:task_id => @task.id)
  end
end

cypress-master/app/helpers/records_helper.rb
module RecordsHelper
  SECTIONS = %w[adverse_event allergy assessment care_experience care_goal communication condition
                device diagnostic_study encounter family_history functional_status immunization intervention
                laboratory_test medical_equipment medication physical_exam preference provider_characteristic
                procedure result risk_category_assessment social_history substance symptom system_characteristic
                transfer vital_sign].freeze
  FIELDS = %w[name principalDiagnosis values dose dischargeDisposition route
              administrationTiming fulfillmentHistory reason direction ordinality
              transferFrom laterality anatomical_location diagnosis].freeze
  SUBFIELDS = %w[title scalar value unit units description period dispenseDate quantityDispensed time].freeze
  CV_POPULATION_KEYS = %w[IPP MSRPOPL MSRPOPLEX OBSERV].freeze
  PROPORTION_POPULATION_KEYS = %w[IPP DENOM NUMER DENEX DENEXCEP].freeze

  def full_gender_name(gender)
    case gender
    when 'M'
      'Male'
    when 'F'
      'Female'
    else
      ''
    end
  end

  def full_name(patient)
    patient.givenNames.join(' ') + ' ' + patient.familyName if patient
  end

  # This method takes a set of result values (as generated by get_result_values)
  # and merges all of the values down to
  # Example input:
  #  {BSON::ObjectId('1')=>{"IPP"=>1, "DENOM"=>0, "DENEX"=>0, "NUMER"=>0, "DENEXCEP"=>0},
  #  BSON::ObjectId('2')=>{"IPP"=>1, "DENOM"=>0, "DENEX"=>0, "NUMER"=>0, "DENEXCEP"=>0},
  #  BSON::ObjectId('3')=>{"IPP"=>1, "DENOM"=>0, "DENEX"=>0, "NUMER"=>0, "DENEXCEP"=>0},}
  #
  # Example output:
  # {"IPP"=>3, "DENOM"=>0, "DENEX"=>0, "NUMER"=>0, "DENEXCEP"=>0}
  def pop_sums(result_values)
    result_values.values.inject do |sum, next_elem|
      sum.merge(next_elem) { |_, key1, key2| key1 + key2 }
    end
  end

  # This method returns a hash of the form
  #  {BSON::ObjectId('1')=>{"IPP"=>1, "DENOM"=>0, "DENEX"=>0, "NUMER"=>0, "DENEXCEP"=>0},
  #  BSON::ObjectId('2')=>{"IPP"=>1, "DENOM"=>0, "DENEX"=>0, "NUMER"=>0, "DENEXCEP"=>0},
  #  BSON::ObjectId('3')=>{"IPP"=>1, "DENOM"=>0, "DENEX"=>0, "NUMER"=>0, "DENEXCEP"=>0},}
  #
  # Inputs:
  # records: An array of records (If you only care about a single record then pass in [record])
  # measures: An array of measures (If you only care about a single measure then pass in [measure])
  # pop_keys: The population keys which you care about, for example ['IPP', 'DENOM']
  # key: The name of the element which should be the key of the key value pair returned.
  # We currently use 'patient_id' and 'measure_id' as keys and then do lookups for the values
  # in the hash when generating miscellaneous views around the Master Patient List.
  #
  # Usage tip: It is strongly recommended you pass in either an array of records OR and array
  # of measures and then pass in the other as an array containing a single element.
  def get_result_values(records, measures, pop_keys, key)
    QDM::IndividualResult.where(
      :patient_id.in => records.collect(&:id),
      :measure_id.in => measures.collect(&:id)
    ).collect do |elem|
      [
        elem[key],
        pop_keys.collect { |pop_key| [pop_key, elem[pop_key].to_i] }.to_h
      ]
    end.to_h
  end

  def records_by_measure(records, measure)
    # Returns array of records that have at least one calculation result for the given measure id
    records.includes(:calculation_results).reject do |r|
      r.calculation_results.select { |c| c['measure'].eql?(measure.id) }.empty?
    end
  end

  def display_field(field)
    display_text = ''
    return '' if field.nil?
    return field if field.is_a? String
    return display_time(field) + "\n" if field.is_a? Integer
    if field.is_a? Array
      field.each { |sub| display_text += display_field(sub) + "\n" }
    else
      field.each do |key, subfield|
        display_text += display_field(subfield) + ' ' if SUBFIELDS.include? key
      end
      field['codes']&.each do |code_system, code|
        display_text += "\n" + code_system + ': ' + code.join(', ')
      end
      display_text += "\n" + field['code_system'] + ': ' + field['code'] if field['code_system']
    end
    display_text
  end

  def coverage_for_measure(measure)
    query_cache_first = QueryCache.where(measure_id: measure.measure_id, sub_id: measure.sub_id, bundle_id: measure.bundle_id, test_id: nil).first
    query_cache_first ? query_cache_first['bonnie_coverage'] : nil
  end

  def hide_patient_calculation?
    # Hide measure calculation if Cypress is in ATL Mode and the current user is not an ATL or admin
    Settings.current.mode_atl? && (!current_user.user_role?('admin') && !current_user.user_role?('atl'))
  end

  def population_label(bundle, pop)
    bundle.modified_population_labels && bundle.modified_population_labels[pop] ? bundle.modified_population_labels[pop] : pop
  end
end

cypress-master/app/views/records/_calculation_result_icon.html.erb
<% if result && result.positive? %>
  <span class="sr-only">Pass</span>
  <span class="fa-stack result-marker">
    <%= icon('fas fa-stack-2x', 'circle', :"aria-hidden" => true) %>
    <% unless result == 1 && !episode_of_care %>
      <strong class="fa-stack-1x result-text"><span class="sr-only">value of </span><%= result %></strong>
    <% end %>
  </span>
<% else %>
  <span class="sr-only">Fail</span>
  <%= icon('far fa-2x empty-marker', 'circle', :"aria-hidden" => true) %>
<% end %>

cypress-master/app/views/records/_calculation_results.html.erb
<% patients.each do |r| %>
  <tr>
    <% if product_test %>
      <td><%= link_to full_name(r), record_path(:id => r.id, :task_id => task.id) %></td>
    <% else %>
      <td><%= link_to full_name(r), bundle_record_path(bundle, r) %></td>
    <% end %>
    <% if product_test && !hide_patient_calculation? %>
      <% original_patient = r.bundle.patients.find(r.extendedData['original_patient']) %>
      <td> <%="#{full_name(original_patient)}"%> </td>
    <%end%>
    <td><%= display_time(r.birthDatetime) %></td>
    <td><%= full_gender_name(r.gender) %></td>
    <!-- will show calculation results for product test records -->
    <% if measure && !(product_test && hide_patient_calculation?) %>
      <% result_values[r.id].each do |_, value| %>
        <td class="text-center">
          <!-- This is the relevant piece of the calculation_result_icon partial ported over to here. Rendering each circle in its own partial is far too slow and causes the application to take up to 8 seconds longer to load on some pages. -->
          <% if value && value.positive? %>
            <span class="sr-only">Pass</span>
            <span class="fa-stack result-marker">
              <%= icon('fas fa-stack-2x', 'circle', :"aria-hidden" => true) %>
              <% unless value == 1 && !measure.episode_of_care %>
                <strong class="fa-stack-1x result-text"><span class="sr-only">value of </span><%= value %></strong>
              <% end %>
            </span>
          <% else %>
            <span class="sr-only">Fail</span>
            <%= icon('far fa-2x empty-marker', 'circle', :"aria-hidden" => true) %>
          <% end %>
        </td>
      <% end %>
    <% end %>
  </tr>
<% end %>

cypress-master/app/views/records/_mpl_download.html.erb
<% current_mpl_status = bundle.mpl_prepare %>
<% if current_mpl_status == :ready %>
  <span class="sr-only">Download <%= bundle.title %></span>
  <%= link_to download_mpl_records_path(bundle), :method => :get, :class => "btn btn-xs btn-default" do %>
    Download <span class="sr-only"><%= bundle.title %></span>
  <% end %>
<% else %>
  <span class="sr-only">Preparing download for <%= bundle.title %></span>
  <%= icon('fas fa-fw fa-spin', 'sync-alt', :"aria-hidden" => true) %> Preparing Download
<% end %>
<% unless current_mpl_status == :ready %>
  <script>
    $(document).ready(function() {
      $.ajax({
        url: "<%= request.env['PATH_INFO'] %>",
        type: "GET",
        dataType: 'script',
        data: { partial: 'mpl_download', mpl_bundle_id: '<%= bundle.id %>' },
        complete: function(data) {
          if(data.status != 200) {
            $('.download-btn#<%= bundle.id %>').html('<b>Error:</b> Please reload webpage')
          }
        }
      });
    });
  </script>
<% end %>

cypress-master/app/views/records/_records_list.html.erb
<!-- Only grab measure records and result values once to avoid duplicate queries -->
<% if measure && patients.length.positive? %>
  <% measure_records = records_by_measure(patients, measure) %>
  <% result_values = get_result_values(patients, [measure], measure.population_ids.keys(), 'patient_id') %>
<% end %>
<h1><%= measure ? measure.display_name : 'All' %> Patients
<% if measure && coverage_for_measure(measure)%>
  - Logic Coverage <%= coverage_for_measure(measure) %>%
<% end %>
</h1>
<% if (measure && measure_records.length.positive?) || (!measure  && patients.length.positive?) %>
<table class="table table-condensed table-hover">
  <thead>
    <tr>
      <th scope="col">Patient Name</th>
      <% if product_test && !hide_patient_calculation? %>
        <th scope="col">Template Name</th>
      <%end%>
      <th scope="col">DOB</th>
      <th scope="col">Gender</th>
      <% if measure && !hide_patient_calculation?%>
        <% measure.population_ids.keys().each do |population| %>
          <th scope="col" class="text-center"><%= population_label(bundle, population) %></th>
        <% end %>
      <% end %>
    </tr>
  </thead>
  <% if measure && !(product_test && hide_patient_calculation?) %>
  <tfoot style="border-top: 2px solid #ddd;">
      <!-- will show aggregate record populations -->
      <tr>
        <th scope="row">Total</th>
        <% if product_test && !hide_patient_calculation? %>
          <td></td>
        <%end%>
        <td></td>
        <td></td>
        <!-- will show calculation results for product test records -->
          <% pop_sums(result_values).each do |_, value| %>
            <td class="text-center">
              <%= render 'calculation_result_icon', :result => value, :episode_of_care => measure.episode_of_care  %>
            </td>
          <% end %>
      </tr>
  </tfoot>
  <% end %>
  <tbody>
    <%= render 'calculation_results',
      :patients => (measure && !product_test) ? measure_records : patients,
      :product_test => product_test,
      :result_values => result_values,
      :bundle => bundle,
      :measure => measure,
      :task => task
    %>
  </tbody>
</table>

<% else %>
<p>No patient results for the current criteria.</p>
<% end %>

cypress-master/app/views/records/by_filter_task.html.erb
<h1>Expected Result Patient List</h1>
<div class="pull-right button-row">
  <% if @measure && @measure.sub_id %>
    <div class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Sub measures <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <% submeasures = HealthDataStandards::CQM::Measure.where(hqmf_id: @measure.hqmf_id).sort_by(&:sub_id) %>
        <% submeasures.each do |submeasure| %>
          <li><%= link_to "#{submeasure.display_name} - #{submeasure.subtitle}", product_test_task_by_filter_task_path(@task.product_test, @task, sub_id: submeasure.sub_id),  method: :get %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= button_to good_results_task_path(@task), :method => :get, :class => "btn btn-default" do %>
    <%= icon('fas fa-fw', 'download', :"aria-hidden" => true) %> Download HTML Patients
  <% end %>
</div>

<% cache [@patients, @measure, hide_patient_calculation?] do %>
  <div class="row">
    <div id="records_list" class="col-sm-12">
      <%= render 'records_list', :patients => @patients, :measure => @measure, :product_test => @product_test, :bundle => @bundle, :task => @task %>
    </div>
  </div>
<% end #cache records %>

cypress-master/app/views/records/by_measure.js.erb
$("#records_list").html("<%= escape_javascript(render 'records_list', :patients => @patients, :measure => @measure, :product_test => @product_test, :bundle => @bundle, :task => @task ) %>");

cypress-master/app/views/records/index.html.erb
<% if @task && @product_test %>

  <h1>Patient List</h1>
  <div class="pull-right button-row">
    <% if @measure && @measure.sub_id %>
      <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Sub measures <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <% submeasures = HealthDataStandards::CQM::Measure.where(hqmf_id: @measure.hqmf_id).sort_by(&:sub_id) %>
          <% submeasures.each do |submeasure| %>
            <li><%= link_to "#{submeasure.display_name} - #{submeasure.subtitle}", { controller: 'records', task_id: @task.id, sub_id: submeasure.sub_id}, method: :get %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= button_to html_patients_product_test_path(@product_test), :method => :get, :class => "btn btn-default" do %>
      <%= icon('fas fa-fw', 'download', :"aria-hidden" => true) %> Download HTML Patients
    <% end %>
  </div>

<% else %>
  <h1>Master Patient List</h1>

  <div class="row">
    <div class="col-md-5 col-sm-6">
      <h1>Filter Patients</h1>
      <div class="form-group">
        <label for="search_measures">Type to search by measure</label>
        <input id="search_measures" type="search" class="form-control" placeholder="Type the name or CMS ID of a measure"/>
      </div>
    </div>

    <% if !@task && !@product_test %>
      <div class="col-md-7 col-sm-6">
        <h1>Annual Update Bundle</h1>
        <div>
          <% if Bundle.available.count == 1 %>
          <div class="radio" style="padding: 6px 0px; display: inline-block">
            <!-- label --> <%= @bundle.title %>
          </div>
          <div class="radio download-btn" id=<%= @bundle.id %>>
            <%= render "mpl_download", :bundle => @bundle %>
          </div>
          <% else %>
            <!-- loop through bundles & use radio buttons -->
            <%= bootstrap_form_tag do |f| %>
              <%= f.form_group :bundle_id do %>
                <% Bundle.available.all.each do |bundle| %>
                  <div style="display: inline-block">
                    <%= f.radio_button :bundle_id, bundle.id, label: bundle.title, label_class: "btn btn-checkbox",
                                       checked: bundle == @bundle %>
                  </div>
                  <div class="radio download-btn" id='<%= bundle.id %>'>
                    <%= render "mpl_download", :bundle => bundle %>
                  </div>
                <% end # bundle loop %>
              <% end # form_group %>
            <% end # form tag %>
          <% end # bundles.count %>
        </div>
      </div>
    <% end %>
  </div>

<% end %>

<% cache [@patients, @measure, hide_patient_calculation?] do %>
  <div class="row">
    <div id="records_list" class="col-sm-12">
      <%= render 'records_list', :patients => @patients, :measure => @measure, :product_test => @product_test, :bundle => @bundle, :task => @task %>
    </div>
  </div>
<% end #cache records %>

<% if !@task || !@product_test %>
<script type="text/javascript">
  // initialize jQueryUI Autocomplete for searching measures
  $('#search_measures').autocomplete({
    delay: 500,
    source: <%= @measure_dropdown %>, // autocomplete suggestions
    select: function(event, data) {  // fired on item select
      // gets records by measure via AJAX and rerender the records list.
      // data.item.value provides the URL for the selected measure
      $.get(data.item.value);
      // autocomplete's default action is to populate the input with the selected value
      // prevent the user from seeing an ugly URL in their search box here
      event.preventDefault();
    },
    focus: function(event, data) { event.preventDefault(); } // fired on item focus
  });

  // add and remove some classes from the generated autocomplete widget
  $('#search_measures').data('ui-autocomplete')._renderItem = function(ul, item) {
    return $('<li class="list-group-item">').append(item.label).appendTo(ul);
  }
  $('#search_measures').data('ui-autocomplete')._renderMenu = function(ul, items) {
    var that = this;
    $.each(items, function(index, item) {
      that._renderItemData(ul, item);
    });
    $(ul).removeClass('ui-widget ui-widget-content').addClass('list-group');
  }

  // rerender the records list to show records from all measures if no value searched
  $('#search_measures').on('keyup', function() {
    if (!$(this).val()) {
      $("#records_list").html("<%= escape_javascript(render 'records_list', :patients => @patients, :measure => @measure, :product_test => @product_test, :bundle => @bundle, :task => @task ) %>");
    }
  })
</script>
<% end %>

cypress-master/app/views/records/index.js.erb
<% if params[:partial] == 'mpl_download' %>
  <% # Can't pass this as bundle_id since bundle_id refers to the active bundle in this context %>
  <% if @mpl_bundle.mpl_status == :ready %>
    <% # don't wait. just load the MPL download %>
    $('.download-btn#<%= @mpl_bundle.id %>').html("<%= escape_javascript render 'mpl_download', :bundle => @mpl_bundle %>");
  <% else %>
    <% # wait 2 seconds. then reload the partial %>
    setTimeout(function(){
      $('.download-btn#<%= @mpl_bundle.id %>').html("<%= escape_javascript render 'mpl_download', :bundle => @mpl_bundle %>");
    }, 2000);
  <% end %>
<% end %>

cypress-master/app/views/records/show.html.erb
<h1>Patient Information for <%= full_name(@record) %></h1>
<div class="row">
<!-- Show measure calculation unless the list is for a product test, Cypress is in ATL Mode and the current user is not an ATL or admin -->
<% unless @product_test && hide_patient_calculation? %>
  <div class="col-md-6">
    <h2>Measure Information</h2>
    <% {
          @continuous_measures => RecordsHelper::CV_POPULATION_KEYS,
          @non_continuous_measures => RecordsHelper::PROPORTION_POPULATION_KEYS
        }.each do |measures, pop_keys| %>
      <% if measures.length.positive? %>
        <table class="table table-condensed">
          <thead>
            <tr>
              <td></td>
              <% pop_keys.each do |population| %>
                <th scope="col" class="text-center"><%= population_label(@bundle, population) %></th>
              <% end %>
            </tr>
          </thead>
          <tbody>
            <% result_values = get_result_values([@record], measures, pop_keys, 'measure_id') %>
            <% measures.each do |m| %>
              <tr>
                <th class="abbreviated" scope="row">
                  <%= m.display_name %>
                </th>
                <% result_values[m.id].each do |population, value| %>
                  <td class="text-center">
                    <span class="sr-only">Measure <%= m.display_name %> population <%= population %> result: </span>
                    <!-- This is the relevant piece of the calculation_result_icon partial ported over to here. Rendering each circle in its own partial is far too slow and causes the application to take up to 8 seconds longer to load on some pages. -->
                    <% if value && value.positive? %>
                      <span class="sr-only">Pass</span>
                      <span class="fa-stack result-marker">
                        <%= icon('fas fa-stack-2x', 'circle', :"aria-hidden" => true) %>
                        <% unless value == 1 && !m.episode_of_care %>
                          <strong class="fa-stack-1x result-text"><span class="sr-only">value of </span><%= value %></strong>
                        <% end %>
                      </span>
                    <% else %>
                      <span class="sr-only">Fail</span>
                      <%= icon('far fa-2x empty-marker', 'circle', :"aria-hidden" => true) %>
                    <% end %>
                  </td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    <% end %>
  </div>
<% end %>

  <div class="col-md-6">
    <h2>Patient Details</h2>
    <dl class="dl-horizontal">
      <dt>DOB</dt><dd><%= display_time(@record.birthDatetime) %></dd>
      <dt>Gender</dt><dd><%= full_gender_name(@record.gender) %></dd>
      <dt>Race</dt><dd><%= @record.get_data_elements('patient_characteristic','race').first['dataElementCodes'].first['descriptor'] %></dd>
      <dt>Ethnicity</dt><dd><%= @record.get_data_elements('patient_characteristic','ethnicity').first['dataElementCodes'].first['descriptor'] %></dd>

      </dl>

    <% RecordsHelper::SECTIONS.each do |s| %>
      <div class="panel panel-default patient-details">
        <div class="panel-heading"><h3 class='panel-title'><%= s.titleize %></h3></div>
          <div class="panel-body">
          <% @record.get_data_elements(s).each do |data| %>
            <%= DataElement.new(data).render.html_safe %>
          <% end %>
          </div>
      </div>
    <% end %>
  </div>
</div>