cypress-master/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  root to: 'home#index'

  get '404', to: 'application#page_not_found'
  get '500', to: 'application#server_error'

  resources :vendors do
    post :favorite
    resources :products, only: %i[show index new create edit update destroy favorite] do
      post :favorite
      member do
        get :patients
        get :report
        get :supplemental_test_artifact
      end
    end
  end

  resources :products, only: %i[show edit update destroy favorite] do
    post :favorite
    resources :product_tests, only: %i[index show]
    resources :checklist_tests, only: %i[create show update destroy] do
      member do
        get :print_criteria
      end
    end
    member do
      get :download_full_test_deck
    end
  end

  resources :checklist_tests, only: %i[create show update destroy] do
    member do
      get 'measure/:measure_id', action: 'measure', as: 'measure'
    end
  end

  resources :product_tests, only: [:show] do
    member do
      get :patients
      get :html_patients
    end
    resources :tasks, only: %i[index show]
    resources :records, only: %i[index show] do
      collection do
        resources :tasks, :controller => :records, :only => [:by_filter_task] do
          get :by_filter_task
        end
      end
    end
  end

  resources :tasks, :only => [:show] do
    member do
      get :good_results
    end
    resources :test_executions, :only => %i[index show new create destroy]
  end

  resources :test_executions, :only => %i[show destroy] do
    member do
      get 'file_result/:file_name', :action => 'file_result', :as => 'file_result'
    end
  end

  resources :bundles, :only => %i[index show] do
    resources :records, :only => %i[index show] do
      collection do
        get :by_measure
      end
    end
    resources :measures, :only => [:index] do
      collection do
        get :grouped
        get 'filtered(/:filter)', :to => 'measures#filtered'
      end
    end
  end

  resources :records, :only => %i[index show] do
    collection do
      get :download_mpl
    end
  end

  resource :admin, :only => [:show], :controller => 'admin'

  namespace 'admin' do
    resource :settings, :only => %i[show edit update]
    get 'users/send_invitation'
    get :download_logs
    resources :users, :except => %i[new create] do
      member do
        get :unlock
        get :toggle_approved
      end
    end
    resources :bundles, :except => %i[show edit update] do
      member do
        post :set_default
        post :deprecate
      end
    end
    resources :trackers, :only => [:destroy]
  end

  get 'terms_and_conditions' => 'static_pages#terms_and_conditions'
end

cypress-master/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include API::Controller
  before_action :set_vendor, only: %i[index new create report patients favorite]
  before_action :set_product, except: %i[index new create]
  before_action :set_measures, only: %i[new edit update report]
  before_action :authorize_vendor
  before_action :require_admin_atl, only: %i[report supplemental_test_artifact]
  before_action :check_bundle_deprecated, only: %i[show edit]
  add_breadcrumb 'Dashboard', :vendors_path

  respond_to :html, except: [:index]
  respond_to :json, :xml, except: %i[new edit update]
  respond_to :js, only: [:favorite]

  def index
    @products = @vendor.products.sort_by { |a| a.favorite_user_ids.include? current_user.id ? 0 : 1 }
    respond_with(@products.to_a)
  end

  def show
    add_breadcrumb 'Vendor: ' + @product.vendor_name, vendor_path(@product.vendor_id)
    add_breadcrumb 'Product: ' + @product.name, vendor_product_path(@product.vendor_id, @product)
    @task = Task.find(params[:task_id]) if params[:task_id]
    respond_with(@product, &:js)
  end

  def new
    @product = Product.new(vendor: @vendor)
    setup_new
  end

  def create
    @product = @vendor.products.new
    @product.update_with_measure_tests(product_params)
    @product.save!
    flash_comment(@product.name, 'success', 'created')
    respond_with(@product) do |f|
      f.html { redirect_to vendor_path(@vendor) }
    end
  rescue Mongoid::Errors::Validations, Mongoid::Errors::DocumentNotFound
    respond_with_errors(@product) do |f|
      f.html do
        setup_new
        @selected_measure_ids = product_params['measure_ids']
        render :new
      end
    end
  end

  def edit
    add_breadcrumb 'Vendor: ' + @product.vendor_name, vendor_path(@product.vendor_id)
    add_breadcrumb 'Product: ' + @product.name, vendor_product_path(@product.vendor_id, @product)
    add_breadcrumb 'Edit Product', :edit_vendor_path
    @selected_measure_ids = @product.measure_ids
  end

  def update
    @product.update_with_measure_tests(edit_product_params)
    @product.save!
    flash_comment(@product.name, 'info', 'edited')
    respond_with(@product) do |f|
      f.html { redirect_to vendor_path(@product.vendor_id) }
    end
  rescue Mongoid::Errors::Validations, Mongoid::Errors::DocumentNotFound
    respond_with(@product) do |f|
      f.html do
        @selected_measure_ids = product_params['measure_ids']
        render :edit
      end
    end
  end

  def destroy
    @product.destroy
    flash_comment(@product.name, 'danger', 'removed')
    respond_with(@product) { |f| f.html { redirect_to vendor_path(@product.vendor_id) } }
  end

  # always responds with a zip file containing information on the certification status of the product
  # includes an html report plus all the test records and files
  def report
    report_content = render_to_string layout: 'report'
    file = Cypress::CreateDownloadZip.create_combined_report_zip(@product, report_content)
    send_data file.read, type: 'application/zip', disposition: 'attachment', filename: "#{@product.name}_#{@product.id}_report.zip".tr(' ', '_')
  end

  def supplemental_test_artifact
    redirect_to(:back, alert: 'Supplement Test Artifact does not exist for this product') && return if @product.supplemental_test_artifact.file.nil?
    send_file @product.supplemental_test_artifact.file.path, disposition: 'attachment'
  end

  # always responds with a zip file of (.qrda.zip files of (qrda category I documents))
  def patients
    crit_exists = !@product.product_tests.checklist_tests.empty?
    filt_exists = !@product.product_tests.filtering_tests.empty?
    criteria_list = crit_exists ? render_to_string(file: 'checklist_tests/print_criteria.html.erb', layout: 'report') : nil
    filtering_list = filt_exists ? render_to_string(file: 'checklist_tests/print_filtering.html.erb', layout: 'report') : nil
    file = Cypress::CreateTotalTestZip.create_total_test_zip(@product, criteria_list, filtering_list, 'qrda')
    send_data file.read, type: 'application/zip', disposition: 'attachment', filename: "#{@product.name}_#{@product.id}.zip".tr(' ', '_')
  end

  def favorite
    deleted_value = @product.favorite_user_ids.delete(current_user.id)
    @product.favorite_user_ids.push(current_user.id) if deleted_value.nil?
    @product.save!
    respond_with(@product)
  end

  private

  def authorize_vendor
    vendor = @vendor || @product.vendor
    authorize_request(vendor, read: %w[report patients])
  end

  def set_measures
    @bundle = @product&.bundle ? @product.bundle : Bundle.default
    @measures = @bundle ? @bundle.measures.top_level.only(:cms_id, :sub_id, :name, :category, :hqmf_id, :type) : []
    @measures_categories = @measures.group_by(&:category)
  end

  def setup_new
    add_breadcrumb 'Vendor: ' + @vendor.name, vendor_path(@product.vendor_id)
    add_breadcrumb 'Add Product', :new_vendor_path
    set_measures
    params[:action] = 'new'
  end

  def product_params
    params[:product][:name]&.strip!
    params.require(:product).permit(:name, :version, :description, :randomize_patients, :duplicate_patients, :shift_patients,
                                    :bundle_id, :measure_selection, :c1_test, :c2_test, :c3_test, :c4_test,
                                    :supplemental_test_artifact, :remove_supplemental_test_artifact, measure_ids: [])
  end

  def edit_product_params
    params[:product][:name]&.strip!
    params.require(:product).permit(:name, :version, :description, :measure_selection, :supplemental_test_artifact,
                                    :remove_supplemental_test_artifact, measure_ids: [])
  end
end

cypress-master/app/helpers/products_helper.rb
# rubocop:disable Metrics/ModuleLength
module ProductsHelper
  # used in product create
  def should_show_product_tests_tab?(product, test_type)
    case test_type
    when 'MeasureTest'
      product.product_tests.measure_tests.any?
    when 'FilteringTest'
      product.product_tests.filtering_tests.any?
    when 'ChecklistTest'
      product.c1_test # should not check for existance of checklist test since there a user can delete checklist tests
    else
      product.product_tests.any?
    end
  end

  def perform_c3_certification_during_measure_test_message(product, test_type)
    return '' unless test_type == 'MeasureTest' && product.c3_test
    certifications = [product.c1_test ? 'C1' : nil, product.c2_test ? 'C2' : nil].compact.join(' and ')
    " C3 certifications will automatically be performed during #{certifications} certifications."
  end

  def set_sorting(test, test_status)
    return 1 if test.state == :queued
    return 2 if test.state == :building

    case test_status
    when 'passing'
      return 6
    when 'failing'
      return 5
    when 'errored'
      return 4
    when 'incomplete'
      return 3
    else
      return 7
    end
  end

  # For pdf
  def all_records_for_product(product)
    records = []
    product.product_tests.each do |pt|
      pt.patients.each do |r|
        new_name = "#{r.first} #{r.last}"
        original_patient = r.bundle.patients.find_by(medical_record_number: r.original_medical_record_number)
        original_name = "#{original_patient.first} #{original_patient.last}"
        records << { new_name: new_name, original: original_name }
      end
    end
    records.any? ? records.sort_by { |r| r[:new_name] }.uniq : records
  end

  # input tasks should be array of (c1 or c2 task) and (c3 task if c3 was selected on product)
  # true if the task's product test is still building or if there is a test execution currently running
  def should_reload_product_test_link?(task_status, test)
    # We should reload if the test is in any state other than ready or errored
    return true unless %i[ready errored].include? test.state
    # We should reload if any tasks are pending
    return true if task_status.eql? 'pending'
    false
  end

  def should_reload_product_test_status_display?(tests)
    tests.each do |test|
      if should_reload_product_test_link?(tasks_status(with_c3_task(test.cat1_task)), test) ||
         should_reload_product_test_link?(tasks_status(with_c3_task(test.cat3_task)), test)
        return true
      end
    end
    false
  end

  def measure_test_running_for_row?(task)
    return true unless %i[ready errored].include? task.product_test_state
    return true if task.most_recent_execution && task.most_recent_execution.status_with_sibling == 'incomplete'
    # Check if the task has been refreshed within the past 30 seconds. If it has then keep refreshing until
    # the database has a chance to settle.
    return true if task.most_recent_execution && (Time.now.utc - task.most_recent_execution.last_updated_with_sibling) < 30
    false
  end

  # Takes a collection of tasks and determines if a measure test is running for any of the tasks.
  # If one is then we need to be refreshing the measure tests table.
  def should_reload_measure_test_table?(tasks)
    tasks.each do |task|
      return true if measure_test_running_for_row?(task)
    end
    false
  end

  # returns the status of the combined tasks for a product test
  #   all tasks must pass to return 'passing'
  #   if one test fails, return 'failing'
  def tasks_status(tasks)
    return 'passing' if tasks.all?(&:passing?)
    return 'failing' if tasks.any?(&:failing?)
    return 'errored' if tasks.any?(&:errored?)
    return 'pending' if tasks.any?(&:pending?)
    return 'incomplete' if tasks.any?(&:incomplete?)
    'unstarted'
  end

  def id_for_html_wrapper_of_task(task)
    "wrapper-task-id-#{task.id}"
  end

  # returns array of tasks. includes a c3 task if it exists
  # input should be a c1 or c2 task
  def with_c3_task(task)
    return [task] unless task.product_test.product.c3_test
    case task
    when C1Task
      return [task, task.product_test.tasks.c3_cat1_task]
    when C2Task
      return [task, task.product_test.tasks.c3_cat3_task]
    end
    [task]
  end

  # yields test_type, title, and description for each tab that should be displayed on product show page
  #   also yeilds html_id which should be used as the html id of the <div> tag that holds the content for each tab
  def each_tab(product)
    %w[ChecklistTest MeasureTest FilteringTest].each do |test_type|
      next unless should_show_product_tests_tab?(product, test_type)
      if test_type == 'MeasureTest'
        title, description, html_id = title_description_and_html_id_for(product, test_type, true)
        yield(test_type, title, description, html_id) if product.c1_test || product.c3_test
        title, description, html_id = title_description_and_html_id_for(product, test_type, false)
        yield(test_type, title, description, html_id) if product.c2_test || product.c3_test
      else
        title, description, html_id = title_description_and_html_id_for(product, test_type)
        yield(test_type, title, description, html_id)
      end
    end
  end

  def title_description_and_html_id_for(product, test_type, is_c1_measure_test = true)
    title = title_for(product, test_type, is_c1_measure_test)
    description = description_for(product, test_type, is_c1_measure_test)
    html_id = html_id_for_tab(product, test_type, is_c1_measure_test)
    [title, description, html_id]
  end

  def html_id_for_tab(product, test_type, is_c1_measure_test = true)
    title_for(product, test_type, is_c1_measure_test).tr(' ', '_').tr('(', '_').tr(')', '_').tr('+', '_').underscore
  end

  # input test_type should only be 'ChecklistTest', 'MeasureTest', or 'FilteringTest'
  # input task_type is only used to differentiate between C1 measure tests and C2 measure test tabs
  def title_for(product, test_type, is_c1_measure_test = true)
    case test_type
    when 'ChecklistTest'
      product.c3_test ? 'C1 + C3 Sample' : 'C1 Sample'
    when 'MeasureTest'
      measure_test_title(product, is_c1_measure_test)
    when 'FilteringTest'
      'C4 (QRDA-I and QRDA-III)'
    end
  end

  def measure_test_title(product, is_c1_measure_test = true)
    if is_c1_measure_test
      if product.c1_test && product.c3_test
        'C1 + C3 (QRDA-I)'
      elsif product.c1_test
        'C1 (QRDA-I)'
      else
        'C3 (QRDA-I)'
      end
    elsif product.c2_test && product.c3_test
      'C2 + C3 (QRDA-III)'
    elsif product.c2_test
      'C2 (QRDA-III)'
    else
      'C3 (QRDA-III)'
    end
  end

  def description_for(product, test_type, is_c1_measure_test = true)
    case test_type
    when 'ChecklistTest'
      certifications = product.c3_test ? 'C1 and C3 certifications' : 'C1 certification'
      "Validate the EHR system for #{certifications} by entering specified patient data for the following measures."
    when 'MeasureTest'
      what_certifications_test_for = if is_c1_measure_test
                                       product.c3_test ? 'record and export (C1) and submit (C3)' : 'record and export (C1)'
                                     else
                                       product.c3_test ? 'import and calculate (C2) and submit (C3)' : 'import and calculate (C2)'
                                     end
      "Test the EHR system's ability to #{what_certifications_test_for} measure based data."
    when 'FilteringTest'
      'Test the EHR system\'s ability to filter patient records.'
    end
  end

  # returns array of tasks (either all C1Tasks or all C2Tasks)
  def measure_test_tasks(product, get_c1_tasks = true)
    # This function was previously sometimes returning results with a false value in front of them,
    # and it would look something like [false, <Task...>], which was then causing problems because
    # we call .first on the returned data. This was causing intermittent test failures, by rejecting
    # blank values we avoid this problem.
    if get_c1_tasks
      product.product_tests.measure_tests.collect { |test| test.tasks.c1_task }.reject(&:blank?)
    else
      product.product_tests.measure_tests.collect { |test| test.tasks.c2_task }.reject(&:blank?)
    end
  end

  def measure_tests_table_row_wrapper_id(task)
    "measure-tests-table-row-wrapper-#{task.id}"
  end

  # Should a C1 or C2 status column be displayed, or only the C3
  def include_first_task(product, first_task_type)
    case first_task_type
    when 'C1Task'
      # True - Display "C1 column" when the first task type being displayed is a C1Task and the product has a C1 test
      # False - Don't display "C1 column" when the product does not have a C1 test
      product.c1_test
    when 'C2Task'
      # True - Display "C2 column" when the first task type being displayed is a C2Task and the product has a C2 test
      # False - Don't display "C2 column" when the product does not have a C2 test
      product.c2_test
    end
  end
end
# rubocop:enable Metrics/ModuleLength

cypress-master/app/views/products/_bulk_download.html.erb
<%
#
# renders the bulk download button if all measure tests are set
#
# must specify local variable "product"
#
%>

<% num_measure_tests = product.product_tests.measure_tests.count %>
<% num_measure_tests_ready = product.product_tests.measure_tests.where(state: :ready).count %>
<% if num_measure_tests_ready == num_measure_tests %>
  <p>This download contains a folder for each measure selected for this product. Inside these folders are XML documents for each patient associated with that measure.</p>
  <%= form_for product, url: patients_vendor_product_path(product.vendor_id, product), :html => { :method => 'GET' } do |f| %>
    <%= button_tag(type: 'submit', class: 'btn btn-primary') do %>
      <%= icon('fas fa-fw', 'download', :"aria-hidden" => true) %> Download All Patients (.zip)
    <% end %>
  <% end %>
<% elsif product.product_tests.measure_tests.where(state: :errored).count.positive? %>
  One or more of the product tests did not build correctly.
<% else %>
  <p>Patient records are being built for each measure.</p>
  <p><%= icon('fas fa-fw fa-spin', 'sync-alt', :"aria-hidden" => true) %><%= " #{num_measure_tests_ready} of #{num_measure_tests} measures ready" %></p>
  <script>
    $.ajax({url: "<%= request.env['PATH_INFO'] %>", type: "GET", dataType: 'script', data: { partial: 'bulk_download' }});
  </script>
<% end %>

cypress-master/app/views/products/_filtering_test_status_display.html.erb
<%

# local variable 'tests' should be filtering_tests

%>
<% tests = product.product_tests.filtering_tests %>

<table class = 'table' id = 'filtering_test_status_display'>
  <thead>
    <th class="no-wrap" scope="col">Filtering Criteria</th>
    <th class="no-wrap" scope="col">QRDA Category I</th>
    <th class="no-wrap" scope="col">QRDA Category III</th>
    <th class="no-wrap" scope="col">Last Updated</th>
  </thead>
  <tbody>
    <% tests.each do |test| %>
      <tr>
        <td class="no-wrap">
          <% if test.display_name.to_s == '' %>
            <%= test.options.filters.keys.join('/').titleize %>
          <% else %>
            <%= test.display_name %>
          <% end %>
        </td>
        <td class="no-wrap" id = "<%= id_for_html_wrapper_of_task(test.cat1_task) %>">
          <%= render 'filtering_test_link', :test => test, :task => test.cat1_task, :parent_reloading => true %>
        </td>
        <td class="no-wrap" id = "<%= id_for_html_wrapper_of_task(test.cat3_task) %>">
          <%= render 'filtering_test_link', :test => test, :task => test.cat3_task, :parent_reloading => true %>
        </td>
        <td class="no-wrap"><%= icon('far fa-fw', 'clock', :"aria-hidden" => true) %>
          <%= local_time_ago(test.updated_at) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if should_reload_product_test_status_display?(tests) %>
  <script>
    $(document).ready(function() {
      $.ajax({url: "<%= request.env['PATH_INFO'] %>", type: "GET", dataType: 'script', data: { partial: 'filtering_test_status_display', html_id: "<%= html_id %>" }});
    });
  </script>
<% end %>

cypress-master/app/views/products/_measure_test_link.html.erb
<%

# local variables
#
#   task  (Task)        for MeasureTest: should be C1Task or C2Task. should NOT be C3Cat1Task or C3Cat3Task since c3 test executions are executed

%>

<% test = task.product_test %>
<% tasks = with_c3_task(task) %>

<% if test.state != :ready %>
  <% if test.state == :queued %>
    <%= icon('far fa-fw text-muted', 'circle', :"aria-hidden" => true) %>
    <span class="label label-default">queued</span>
  <% elsif test.state == :building %>
    <%= icon('fas fa-fw fa-spin', 'cog', :"aria-hidden" => true) %>
    <span class="label label-default">building</span>
  <% elsif test.state == :errored %>
    <%= icon('fas', 'exclamation-triangle', :"aria-hidden" => true) %>
  <% end %>
<% else %>
  <% case tasks_status(tasks) %>
  <% when 'pending' %>
    <%= icon('fas fa-fw fa-spin text-testing', 'gavel', :"aria-hidden" => true) %>
    <span class = 'label label-default'>testing...</span>
  <% else %>
    <%= icon('fas fa-fw invisible', 'gavel', :"aria-hidden" => true) %>
    <%= render partial: '/products/product_test_upload', locals: { task: task, label_class: 'label-info' } %>
  <% end %>
<% end %>

cypress-master/app/views/products/_measure_tests_table.html.erb
<%

# local variables
#
#   product (The parent product we are fetching tasks for)
#   get_c1_tasks (whether the measure tasks we fetch should include c1 tasks)

%>
<% # Convert get_c1_tasks into a boolean if it is a string. %>
<% get_c1_tasks = get_c1_tasks.eql? "true" if get_c1_tasks.is_a? String %>
<% tasks = measure_test_tasks(product, get_c1_tasks) %>
<% return unless tasks.any? %>

<% first_results_col_label = tasks.first.is_a?(C1Task) ? 'C1 Results' : 'C2 Results' %>
<% include_c3 = product.c3_test %>

<table class = 'table table-hover measure_tests_table'>
  <thead>
    <th scope = 'col' class = 'col-sm-1 no-wrap pointer-on-hover'>CMS ID</th>
    <th scope = 'col' class = 'col-sm-4 pointer-on-hover'>Measure Name</th>
    <% if include_first_task(product, tasks.first._type) %>
      <th scope = 'col' class = 'col-sm-2 no-wrap pointer-on-hover'><%= first_results_col_label %></th>
    <% end %>
    <% if include_c3 %>
      <th scope = 'col' class = 'col-sm-2 no-wrap pointer-on-hover'>C3 Results</th>
    <% end %>
    <th scope = 'col' class = 'col-sm-1'>Quick Upload</th>
    <th scope = 'col' class = 'col-sm-1'>Last Updated</th>
  </thead>
  <tbody>
    <% tasks.sort_by { |t| cms_int(t.product_test.cms_id) }.each do |task| %>
      <tr id = '<%= measure_tests_table_row_wrapper_id(task) %>'>
        <%= render 'measure_tests_table_row', :task => task, :parent_reloading => true %>
      </tr>
    <% end %>
  </tbody>
</table>

<script>
  $('.measure_tests_table').DataTable({
    destroy: true,
    searching: false,
    paging: false,
    stateSave: true, /* preserves order on reload */
    info: false
  });
</script>

<% if should_reload_measure_test_table?(tasks) %>
  <script>
    $(document).ready(function() {
      $.ajax({url: "<%= request.env['PATH_INFO'] %>", type: "GET", dataType: 'script', data: { partial: 'measure_tests_table', should_include_c1: "<%= get_c1_tasks %>", html_id: "<%= html_id %>" }});
    });
  </script>
<% end %>

cypress-master/app/views/products/_measure_tests_table_row.html.erb
<%

# local variables
#
#   task       (Task)
#   parent_reloading is a boolean stating whether or not the measure_tests_table is already reloading via ajax, in order to make
#   sure we don't reload at the same time and double up on requests.
%>

<% parent_reloading = false unless (defined? parent_reloading) %>

<% test = task.product_test %>
<% include_c3 = test.product.c3_test %>

<td data-sort="<%= cms_int(test.cms_id) %>"><%= test.cms_id %></td>
<td><%= link_to test.name, new_task_test_execution_path(task) %></td>
<% if include_first_task(test.product, task._type) %>
  <td data-order="<%= set_sorting(test, task.status) %>">
    <%= render 'execution_status_message', :execution => task.most_recent_execution, :test_state => test.state %>
  </td>
<% end %>
<% if include_c3 %>
  <% sibling_execution = task.most_recent_execution ? task.most_recent_execution.sibling_execution : nil %>
  <td data-order="<%= set_sorting(test, task.status) %>">
    <%= render 'execution_status_message', :execution => sibling_execution, :test_state => test.state %>
  </td>
<% end %>
<td id = "<%= id_for_html_wrapper_of_task(task) %>" class="no-wrap" data-order="<%= set_sorting(test, task.status) %>">
  <%= render partial: '/products/measure_test_link', locals: { test: test, task: task } %>
</td>
<td class="no-wrap" data-order="<%= task.updated_at %>">
  <%= icon('far fa-fw', 'clock', :"aria-hidden" => true) %><%= local_time_ago(task.updated_at) %>
</td>

<% # Only reload if the measure_tests_table isn't reloading for us. (This currently only happens in create.js.erb) %>
<% if measure_test_running_for_row?(task) && !parent_reloading %>
  <script>
    $(document).ready(function() {
      $.ajax({url: "<%= request.env['PATH_INFO'] %>", type: "GET", dataType: 'script', data: { partial: 'measure_tests_table_row', task_id: "<%= task.id.to_s %>" }});
    });
  </script>
<% end %>

cypress-master/app/views/products/_product_test_upload.html.erb
<%

# local variables:
#
#   task
#   label_class [optional]

%>

<% label_class ||= 'label-default' %>

<% accept_type = displaying_cat1?(task) ? 'application/zip' : 'text/xml' %>
<% unique_id = task.id # value unique to this form %>

<%= form_for(TestExecution.new, html: { method: :post, multipart: true, id: "multi-upload-form-#{unique_id}", class: 'inline' }, :authenticity_token => true, remote: true, url: task_test_executions_path(task)) do |f| %>
  <%= f.label :results, 'upload', class: "inline label #{label_class} pointer-on-hover", for: "multi-upload-field-#{unique_id}" do %>
     upload<%= f.file_field :results, class: 'hidden multi-upload-field', accept: accept_type, id: "multi-upload-field-#{unique_id}" %>
  <% end %>
  <%= f.submit 'my submit button', class: 'hidden multi-upload-submit', id: "multi-upload-submit-#{unique_id}" %>
<% end %>

cypress-master/app/views/products/edit.html.erb
<%= render 'action_modal' %>

<%= render 'product_form', :submit_text => "Edit Product", :product => @product, :bundle => @bundle, :measures_categories => @measures_categories, :selected_measure_ids => @selected_measure_ids %>

<%= render 'remove_panel', :name => @product.name, :type => 'product', :message => 'Removing a product will also delete all associated product tests and test execution results. Be sure you want to do this.', :delete_path => vendor_product_path(@product.vendor_id, @product) %>

cypress-master/app/views/products/show.html.erb
<%= render 'header_product', :product => @product %>
<div class="row">

  <div class = 'col-md-8'>
    <%= render 'product_status_table', :product => @product %>
  </div>

  <div class = 'col-md-4'>
    <% unless @product.product_tests.empty? %>
      <div class = 'panel panel-default'>
        <div class = 'panel-heading'>
          <h1 class='panel-title'>Download Full Test Deck</h1>
        </div>
        <div class = 'panel-body' id = 'display_bulk_download'>
          <%= render 'bulk_download', :product => @product %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="product-test-tabs">
  <ul>
    <% each_tab(@product) do |test_type, title, _, html_id| %>
      <li><a href = '<%= "##{html_id}" %>'><%= title %></a></li>
    <% end %>
  </ul>

  <% each_tab(@product) do |test_type, title, description, html_id| %>
    <div id = '<%= html_id %>'>
      <p class = 'lead'><%= description %></p>

      <% # Record Sample Tab %>
      <% if test_type == 'ChecklistTest' %>
        <% checklist_test = @product.product_tests.checklist_tests.first %>
        <%= button_to 'View Record Sample', product_checklist_test_path(@product, checklist_test), class: 'btn btn-primary', method: :get %><p></p>
        <div id = 'display_checklist_execution_results'>
          <%= render 'checklist_execution_results', :task => @product.product_tests.checklist_tests.first.tasks.c1_checklist_task %>
        </div>
        <% has_many_measures = checklist_test.measures.count > CAT1_CONFIG['number_of_checklist_measures'] %>
        <%= render 'checklist_status_display', :product => @product, :has_many_measures => has_many_measures %>
      <% end %>

      <% # Measure Test Tabs (both C1 or C2 tabs) %>
      <% if test_type == 'MeasureTest' %>
        <div id="display_measure_tests_table">
          <%= render 'measure_tests_table', :product => @product, :get_c1_tasks => (title.include?('C1') || title.include?('C3') && !title.include?('QRDA-III')),
            :html_id => html_id  %>
        </div>
      <% end %>

      <% # Filtering Test Tab %>
      <% if test_type == 'FilteringTest' %>
        <div id="display_filtering_test_status_display">
          <%= render 'filtering_test_status_display', :product => @product, :html_id => html_id %>
        </div>
      <% end %>

    </div>
  <% end %>
</div>