cypress-master/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  root to: 'home#index'

  get '404', to: 'application#page_not_found'
  get '500', to: 'application#server_error'

  resources :vendors do
    post :favorite
    resources :products, only: %i[show index new create edit update destroy favorite] do
      post :favorite
      member do
        get :patients
        get :report
        get :supplemental_test_artifact
      end
    end
  end

  resources :products, only: %i[show edit update destroy favorite] do
    post :favorite
    resources :product_tests, only: %i[index show]
    resources :checklist_tests, only: %i[create show update destroy] do
      member do
        get :print_criteria
      end
    end
    member do
      get :download_full_test_deck
    end
  end

  resources :checklist_tests, only: %i[create show update destroy] do
    member do
      get 'measure/:measure_id', action: 'measure', as: 'measure'
    end
  end

  resources :product_tests, only: [:show] do
    member do
      get :patients
      get :html_patients
    end
    resources :tasks, only: %i[index show]
    resources :records, only: %i[index show] do
      collection do
        resources :tasks, :controller => :records, :only => [:by_filter_task] do
          get :by_filter_task
        end
      end
    end
  end

  resources :tasks, :only => [:show] do
    member do
      get :good_results
    end
    resources :test_executions, :only => %i[index show new create destroy]
  end

  resources :test_executions, :only => %i[show destroy] do
    member do
      get 'file_result/:file_name', :action => 'file_result', :as => 'file_result'
    end
  end

  resources :bundles, :only => %i[index show] do
    resources :records, :only => %i[index show] do
      collection do
        get :by_measure
      end
    end
    resources :measures, :only => [:index] do
      collection do
        get :grouped
        get 'filtered(/:filter)', :to => 'measures#filtered'
      end
    end
  end

  resources :records, :only => %i[index show] do
    collection do
      get :download_mpl
    end
  end

  resource :admin, :only => [:show], :controller => 'admin'

  namespace 'admin' do
    resource :settings, :only => %i[show edit update]
    get 'users/send_invitation'
    get :download_logs
    resources :users, :except => %i[new create] do
      member do
        get :unlock
        get :toggle_approved
      end
    end
    resources :bundles, :except => %i[show edit update] do
      member do
        post :set_default
        post :deprecate
      end
    end
    resources :trackers, :only => [:destroy]
  end

  get 'terms_and_conditions' => 'static_pages#terms_and_conditions'
end

cypress-master/app/models/user.rb
class User
  include Mongoid::Document
  rolify
  # Include default devise modules. Others available are:
  # :confirmable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :timeoutable, :lockable, :invitable,
         :confirmable

  # confirmable
  field  :confirmation_token, type: String
  field  :confirmed_at, type: Time, default: proc { Settings.current.auto_confirm ? Time.now.in_time_zone : nil }
  field  :confirmation_sent_at, type: Time
  ## Database authenticatable
  field :email,              type: String, default: ''
  field :unconfirmed_email
  field :encrypted_password, type: String, default: ''

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Lockable
  field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  field :locked_at,       type: Time

  ## invitable
  field :invitation_token, type: String
  field :invitation_created_at, type: Time
  field :invitation_sent_at, type: Time
  field :invitation_accepted_at, type: Time
  field :invitation_limit, type: Integer

  has_many :test_executions, :dependent => :nullify

  index(:invitation_token => 1)
  index(:invitation_by_id => 1)

  field :approved, :type => Boolean, :default => proc { Settings.current.auto_approve || false }

  validates :terms_and_conditions, :acceptance => true, :on => :create, :allow_nil => false

  after_create :associate_points_of_contact
  after_create :assign_default_role

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else
      super # Use whatever other message
    end
  end

  validate :password_complexity

  def password_complexity
    if password.present?
      # returns nil if no match, index of match otherwise
      lowcase = password =~ /^(?=.*[a-z])./
      upcase = password =~ /^(?=.*[A-Z])./
      num = password =~ /^(?=.*[\d])./
      special = password =~ /^(?=.*[\W])./
      unless [lowcase, upcase, num, special].compact.length >= 3
        errors.add :password, 'password must include at least 3 of the following: lowercase letters, uppercase letters, digits, special characters'
      end
      errors.add :password, 'email and password must be different' if password == email
    end
  end

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  def associate_points_of_contact
    if Settings.current.auto_associate_pocs
      Vendor.where('points_of_contact.email' => email).by_updated_at.each do |vendor|
        add_role :vendor, vendor
      end
    end
  end

  def assign_default_role
    dr = Settings.current.default_role
    add_role dr if dr.present?
  end

  def user_role?(*args)
    has_role?(*args) || Settings.current.ignore_roles
  end

  def assign_roles_and_email(params)
    self.roles = []
    add_role params[:role]
    self.email = params[:user][:email] if params[:user] && params[:user][:email]
    assignments = params[:assignments].values if params[:assignments]
    (assignments || []).each do |ass|
      add_role(ass[:role], Vendor.find(ass[:vendor_id]))
    end
    save
  end

  def unlock
    self.locked_at = nil
    self.failed_attempts = 0
    self.unlock_token = nil
    save
  end
end

cypress-master/app/controllers/admin/users_controller.rb
module Admin
  class UsersController < AdminController
    def index
      redirect_to admin_path(anchor: 'user_management')
    end

    def edit
      add_breadcrumb 'Edit Users', :edit_users_path
      @user = User.find(params[:id])
    end

    def show
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      @user.assign_roles_and_email(params)
      flash[:notice] = 'Successfully updated user.'
      redirect_to_admin
    end

    def send_invitation
      User.invite!(email: params[:email])
      redirect_to_admin
    end

    def toggle_approved
      @user = User.find(params[:id])
      @user.approved = !@user.approved
      @user.save
      redirect_to_admin
    end

    def unlock
      @user = User.find(params[:id])
      @user.unlock
      redirect_to_admin
    end

    def destroy
      @user = User.find(params[:id])
      if @user.destroy
        flash[:notice] = 'Successfully deleted User.'
        redirect_to_admin
      end
    end

    private

    def redirect_to_admin
      redirect_to "#{admin_path}#user_management"
    end
  end
end

cypress-master/app/helpers/users_helper.rb
module UsersHelper
  def options_for_owner_vendor
    options_for_select([%w[Owner owner], %w[Vendor vendor]])
  end
end

cypress-master/app/views/admin/users/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class='panel-title'>Edit User</h1>
  </div>
  <%= bootstrap_form_for(@user, as: @user, url: admin_user_path(@user), html: { method: :put, 'data-parsley-validate': '' }) do |f| %>
  <div class="panel-body">
    <div class="col-md-6">
      <%= f.email_field :email, autocapitalize: 'off', autocorrect: 'off', autofocus: true,
      'data-parsley-required': '',
      'data-parsley-type': 'email',
      'data-parsley-trigger': 'blur' %>
      <% if @user.pending_reconfirmation? %>
        <div>Currently waiting confirmation for: <%= @user.unconfirmed_email %></div>
      <% end %>


      <div class="form_group">
        <label class="control-label" for="user_role">Role</label>
        <ul class="list-unstyled">
          <li><input id="admin_radio" type="radio" name="role" value="admin" <%= "checked='true'" if @user.has_role? :admin %>> Admin</li>
          <li><input id="atl_radio" type="radio" name="role" value="atl" <%= "checked='true'" if @user.has_role? :atl %>> Atl</li>
          <li><input id="user_radio" type="radio" name="role" value="user" <%= "checked='true'" if @user.has_role? :user %>> User</li>
        </ul>
      </div>
    </div>
    <div class="col-md-6">
      Assignments:
      <div class="form_group">
       <label for="role_select">Role </label> <select id="role_select" class="selectpicker"><%= options_for_owner_vendor() %></select>
       <label for="vendor_select">Vendor </label> <select id="vendor_select" class="selectpicker"><%= options_for_select(Vendor.all.collect{|v| [v.name,v.id]}) %></select>
       <button id="addAssignment" name="Add Assignment" >Add Assigment </button>
      </div>
        <div >
              <table class="table" id="assignments">
     <% @user.roles.where({resource_id: {"$ne" => nil}}).each_with_index do |r, index| %>

              <tr>
                <td class="col-sm-3"> <%= r.name%></td>
                <td class="col-sm-9"> <%= r.resource.name %></td>
                <td>
                  <input type="hidden" name="assignments[<%= index %>][role]" value="<%= r.name %>"/>
                  <input type="hidden" name="assignments[<%= index %>][vendor_id]" value="<%= r.resource_id %>"/>
                  <button onclick="$(this).parent().parent().remove(); return false" >Remove </button>
                </td>
              </tr>
     <% end %>
       </table>
      </div>
    </div>

  </div>
  <div class="panel-footer">
   <button class="btn btn-default" >Edit User</button> <a class="btn btn-default"  href="<%= admin_path + '#user_management' %>"> Cancel</a>
  </div>
  <% end %>
</div>

  <%= render 'action_modal' %>
<%= render 'remove_panel', :name => @user.email, :type => 'user', :message => ' Be sure you want to do this.', :delete_path => admin_user_path(@user) %>

cypress-master/app/views/admin/users/index.html.erb
<div class="col-md-12">
<table class="table">
  <thead>
    <tr>
      <th>Email</th>
      <th>Role</th>
      <th>Approved</th>
      <th>Assignments</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user|
    role = user.roles.where({resource_id: nil}).first
    assignments = user.roles.where({resource_id: {"$ne"=> nil}})
    %>
    <tr>
      <td><%= user.email %></td>
      <td><%= role.name if role %></td>
      <td><a href="<%= toggle_approved_admin_user_path(user) %>" data-turbolinks-action="replace"><%= user.approved %></a></td>
      <td>
        <table class"table">
          <% assignments.each do |ass|
            if ass.resource
          %>
          <tr><td class="col-sm-3"><%= ass.name %></td><td class="col-sm-9"><%= ass.resource.name %></td></tr>
        <%  end
          end
       %>
        </table>
      </td>
      <td><a class="btn btn-default" href="<%= edit_admin_user_path(user) %>"><%= icon('fas fa-fw', 'wrench', :"aria-hidden" => true) %>Edit User </a></td>
    </tr>
    <% end %>
  </tbody>

</table>

</div>